image:
  - Visual Studio 2015
  # - Visual Studio 2017

install:
  - ps: choco install codecov

# disable msbuild:
build: off

# use build script instead:
build_script:
  - cmd: build.cmd

test_script:
  - cmd: runAltcover.cmd
  - cmd: copy .\codecoverage\BusyCoverage.xml .\BusyCoverage.xml
      # Upload coverage results to codecov.io
  - ps: $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
  - ps: bash codecov.sh -f "BusyCoverage.xml"  