image:
  - Visual Studio 2019

install:
  - ps: choco install codecov

# disable msbuild:
build: off

# use build script instead:
build_script:
  - cmd: build.cmd

test_script:
  - cmd: runAltcover.cmd
  - cmd: copy .\codecoverage\BusyCoverage.xml .\BusyCoverage.xml
      # Upload coverage results to codecov.io
  - ps: $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
  - cmd: codecov -f "BusyCoverage.xml"  
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Join-Path $env:APPVEYOR_BUILD_FOLDER .\tests\Busy.Tests\bin\Debug\netcoreapp3.1\Busy.Tests.TestResults.xml))