// Auto-Generated by FAKE; do not edit
namespace System
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("Busy.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "Busy.Tests"
